insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("로지텍 g100", "Electronic", 80000, "LG", 130, "마우스")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("그램 17인치", "Electronic", 1800000, "LG", 50, "노트북")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("IPhone 12", "Electronic", 1400000, "Apple", 80, "핸드폰")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("명품 Java Programming", "Book", 32000, "생능출판", 40, "컴퓨터 언어 책")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("AirPods Pro", "Electronic", 320000, "Apple", 4, "무선이어폰")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("IPad Air", "Electronic", 800000, "Apple", 19, "아이패드")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("명품 C Programming", "Book", 30000, "생능출판", 40, "컴퓨터 언어 책")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("휘센", "Home appliances", 880000, "Samsung", 15, "에어콘")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("아프니까 청춘이다", "Book", 25000, "한빛미디어", 20, "자기개발책")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("Galaxy Note 5", "Electronic", 1500000, "Samsung", 66, "휴대폰")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("트롬", "Home appliances", 550000, "Samsung", 33, "세탁기")